server:
  port: 8005
  error:
    include-message: always
spring:
  profiles:
    active: dev

  datasource:
    driverClassName: com.mysql.jdbc.Driver
#    username: root
#    password: qghhPLyLVgqzACZnHMJCDpVeqpjSYrNi
#    url: jdbc:mysql://viaduct.proxy.rlwy.net:22270/railway

#    username: root
#    password:
#    url: jdbc:mysql://localhost:3307/customerdatabase?zeroDateTimeBehavior=convertToNull&useSSL=false

    username: nsqauser1
    password: RDexdyt9
    url: jdbc:mysql://localhost:3307/nsqa080624?zeroDateTimeBehavior=convertToNull&useSSL=false

#    URL: jdbc:mysql://backupdb.nstyleintl.com:3307/nsqa080624?zeroDateTimeBehavior=convertToNull&useSSL=false
#    username: nsqauser1
#    password: RDexdyt9
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy 
    show-sql: false
    properties:
      hibernate: 
    database-platform: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org.springframework: DEBUG